<link rel="manifest" href="/manifest.json">
<!-- Add to home screen for Safari on iOS -->
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<meta name="apple-mobile-web-app-title" content="fiora">
<link rel="apple-touch-icon" href="https://cdn.suisuijiang.com/ImageMessage/5adad39555703565e79040fa_1535893328317.png">
<!-- Windows -->
<meta name="msapplication-TileImage" content="https://cdn.suisuijiang.com/ImageMessage/5adad39555703565e79040fa_1535893328317.png">
<meta name="msapplication-TileColor" content="#333">